---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: webchat-go

spec:
  replicas: 1
  selector:
    matchLabels:
      name: webchat-go
  template:
    metadata:
      labels:
        name: webchat-go
    spec:
      containers:
      - name: application
        image: cjavan/webchat-go
        ports:
         - containerPort: 8080