---
apiVersion: v1
kind: Service

metadata:
  name: caddy-go-service

spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
  selector:
    name: webchat-caddy